-- audit table for Trigger-01 question
SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE auditEmployee (
        audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        e_id NUMBER,
        e_name VARCHAR2(50),
        hire_date DATE,
        action_date DATE,
        action_type VARCHAR2(10)
    )'; 
    DBMS_OUTPUT.PUT_LINE('Table auditEmployee created successfully.');
END;
/

SELECT * FROM auditEmployee;
-- SELECT 1 from dual;